// <auto-generated />
using System;
using Gamemode.Repositories.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Gamemode.Migrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20210320090921_Fraction")]
    partial class Fraction
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Gamemode.Repositories.Models.AdminRank", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("admin_rank");

                    b.HasData(
                        new
                        {
                            Id = (byte)1,
                            Name = "Junior"
                        },
                        new
                        {
                            Id = (byte)2,
                            Name = "Middle"
                        },
                        new
                        {
                            Id = (byte)3,
                            Name = "Senior"
                        },
                        new
                        {
                            Id = (byte)4,
                            Name = "Lead"
                        },
                        new
                        {
                            Id = (byte)5,
                            Name = "Owner"
                        });
                });

            modelBuilder.Entity("Gamemode.Repositories.Models.Fraction", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("fraction");

                    b.HasData(
                        new
                        {
                            Id = (byte)1,
                            Name = "Bloods"
                        },
                        new
                        {
                            Id = (byte)2,
                            Name = "Ballas"
                        },
                        new
                        {
                            Id = (byte)3,
                            Name = "The Families"
                        },
                        new
                        {
                            Id = (byte)4,
                            Name = "Vagos"
                        },
                        new
                        {
                            Id = (byte)5,
                            Name = "Marabunta Grande"
                        });
                });

            modelBuilder.Entity("Gamemode.Repositories.Models.FractionRank", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    b.Property<byte?>("FractionId")
                        .HasColumnType("smallint")
                        .HasColumnName("fraction_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("name");

                    b.Property<byte>("Tier")
                        .HasColumnType("smallint")
                        .HasColumnName("tier");

                    b.HasKey("Id");

                    b.HasIndex("FractionId");

                    b.HasIndex("Id", "Name")
                        .IsUnique();

                    b.HasIndex("Id", "Tier")
                        .IsUnique();

                    b.ToTable("fraction_rank");

                    b.HasData(
                        new
                        {
                            Id = (byte)1,
                            FractionId = (byte)1,
                            Name = "Bloods1",
                            Tier = (byte)1
                        },
                        new
                        {
                            Id = (byte)2,
                            FractionId = (byte)1,
                            Name = "Bloods2",
                            Tier = (byte)2
                        },
                        new
                        {
                            Id = (byte)3,
                            FractionId = (byte)1,
                            Name = "Bloods3",
                            Tier = (byte)3
                        },
                        new
                        {
                            Id = (byte)4,
                            FractionId = (byte)1,
                            Name = "Bloods4",
                            Tier = (byte)4
                        },
                        new
                        {
                            Id = (byte)5,
                            FractionId = (byte)1,
                            Name = "Bloods5",
                            Tier = (byte)5
                        },
                        new
                        {
                            Id = (byte)6,
                            FractionId = (byte)1,
                            Name = "Bloods6",
                            Tier = (byte)6
                        },
                        new
                        {
                            Id = (byte)7,
                            FractionId = (byte)1,
                            Name = "Bloods7",
                            Tier = (byte)7
                        },
                        new
                        {
                            Id = (byte)8,
                            FractionId = (byte)1,
                            Name = "Bloods8",
                            Tier = (byte)8
                        },
                        new
                        {
                            Id = (byte)9,
                            FractionId = (byte)1,
                            Name = "Bloods9",
                            Tier = (byte)9
                        },
                        new
                        {
                            Id = (byte)10,
                            FractionId = (byte)1,
                            Name = "Bloods10",
                            Tier = (byte)10
                        },
                        new
                        {
                            Id = (byte)11,
                            FractionId = (byte)2,
                            Name = "Блайд",
                            Tier = (byte)1
                        },
                        new
                        {
                            Id = (byte)12,
                            FractionId = (byte)2,
                            Name = "Бастер",
                            Tier = (byte)2
                        },
                        new
                        {
                            Id = (byte)13,
                            FractionId = (byte)2,
                            Name = "Крэкер",
                            Tier = (byte)3
                        },
                        new
                        {
                            Id = (byte)14,
                            FractionId = (byte)2,
                            Name = "Гун бро",
                            Tier = (byte)4
                        },
                        new
                        {
                            Id = (byte)15,
                            FractionId = (byte)2,
                            Name = "Ап бро",
                            Tier = (byte)5
                        },
                        new
                        {
                            Id = (byte)16,
                            FractionId = (byte)2,
                            Name = "Гангстер",
                            Tier = (byte)6
                        },
                        new
                        {
                            Id = (byte)17,
                            FractionId = (byte)2,
                            Name = "Федерал блок",
                            Tier = (byte)7
                        },
                        new
                        {
                            Id = (byte)18,
                            FractionId = (byte)2,
                            Name = "Фолкс",
                            Tier = (byte)8
                        },
                        new
                        {
                            Id = (byte)19,
                            FractionId = (byte)2,
                            Name = "Райч нига",
                            Tier = (byte)9
                        },
                        new
                        {
                            Id = (byte)20,
                            FractionId = (byte)2,
                            Name = "Биг вилли",
                            Tier = (byte)10
                        },
                        new
                        {
                            Id = (byte)21,
                            FractionId = (byte)3,
                            Name = "Bloods11",
                            Tier = (byte)1
                        },
                        new
                        {
                            Id = (byte)22,
                            FractionId = (byte)3,
                            Name = "Bloods12",
                            Tier = (byte)2
                        },
                        new
                        {
                            Id = (byte)23,
                            FractionId = (byte)3,
                            Name = "Bloods13",
                            Tier = (byte)3
                        },
                        new
                        {
                            Id = (byte)24,
                            FractionId = (byte)3,
                            Name = "Bloods14",
                            Tier = (byte)4
                        },
                        new
                        {
                            Id = (byte)25,
                            FractionId = (byte)3,
                            Name = "Bloods15",
                            Tier = (byte)5
                        },
                        new
                        {
                            Id = (byte)26,
                            FractionId = (byte)3,
                            Name = "Bloods16",
                            Tier = (byte)6
                        },
                        new
                        {
                            Id = (byte)27,
                            FractionId = (byte)3,
                            Name = "Bloods17",
                            Tier = (byte)7
                        },
                        new
                        {
                            Id = (byte)28,
                            FractionId = (byte)3,
                            Name = "Bloods18",
                            Tier = (byte)8
                        },
                        new
                        {
                            Id = (byte)29,
                            FractionId = (byte)3,
                            Name = "Bloods19",
                            Tier = (byte)9
                        },
                        new
                        {
                            Id = (byte)30,
                            FractionId = (byte)3,
                            Name = "Bloods20",
                            Tier = (byte)10
                        },
                        new
                        {
                            Id = (byte)31,
                            FractionId = (byte)4,
                            Name = "Bloods21",
                            Tier = (byte)1
                        },
                        new
                        {
                            Id = (byte)32,
                            FractionId = (byte)4,
                            Name = "Bloods22",
                            Tier = (byte)2
                        },
                        new
                        {
                            Id = (byte)33,
                            FractionId = (byte)4,
                            Name = "Bloods23",
                            Tier = (byte)3
                        },
                        new
                        {
                            Id = (byte)34,
                            FractionId = (byte)4,
                            Name = "Bloods24",
                            Tier = (byte)4
                        },
                        new
                        {
                            Id = (byte)35,
                            FractionId = (byte)4,
                            Name = "Bloods25",
                            Tier = (byte)5
                        },
                        new
                        {
                            Id = (byte)36,
                            FractionId = (byte)4,
                            Name = "Bloods26",
                            Tier = (byte)6
                        },
                        new
                        {
                            Id = (byte)37,
                            FractionId = (byte)4,
                            Name = "Bloods27",
                            Tier = (byte)7
                        },
                        new
                        {
                            Id = (byte)38,
                            FractionId = (byte)4,
                            Name = "Bloods28",
                            Tier = (byte)8
                        },
                        new
                        {
                            Id = (byte)39,
                            FractionId = (byte)4,
                            Name = "Bloods29",
                            Tier = (byte)9
                        },
                        new
                        {
                            Id = (byte)40,
                            FractionId = (byte)4,
                            Name = "Bloods30",
                            Tier = (byte)10
                        },
                        new
                        {
                            Id = (byte)41,
                            FractionId = (byte)5,
                            Name = "Bloods31",
                            Tier = (byte)1
                        },
                        new
                        {
                            Id = (byte)42,
                            FractionId = (byte)5,
                            Name = "Bloods32",
                            Tier = (byte)2
                        },
                        new
                        {
                            Id = (byte)43,
                            FractionId = (byte)5,
                            Name = "Bloods33",
                            Tier = (byte)3
                        },
                        new
                        {
                            Id = (byte)44,
                            FractionId = (byte)5,
                            Name = "Bloods34",
                            Tier = (byte)4
                        },
                        new
                        {
                            Id = (byte)45,
                            FractionId = (byte)5,
                            Name = "Bloods35",
                            Tier = (byte)5
                        },
                        new
                        {
                            Id = (byte)46,
                            FractionId = (byte)5,
                            Name = "Bloods36",
                            Tier = (byte)6
                        },
                        new
                        {
                            Id = (byte)47,
                            FractionId = (byte)5,
                            Name = "Bloods37",
                            Tier = (byte)7
                        },
                        new
                        {
                            Id = (byte)48,
                            FractionId = (byte)5,
                            Name = "Bloods38",
                            Tier = (byte)8
                        },
                        new
                        {
                            Id = (byte)49,
                            FractionId = (byte)5,
                            Name = "Bloods39",
                            Tier = (byte)9
                        },
                        new
                        {
                            Id = (byte)50,
                            FractionId = (byte)5,
                            Name = "Bloods40",
                            Tier = (byte)10
                        });
                });

            modelBuilder.Entity("Gamemode.Repositories.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<byte?>("AdminRankId")
                        .HasColumnType("smallint")
                        .HasColumnName("admin_rank_id");

                    b.Property<string>("BanReason")
                        .HasColumnType("text")
                        .HasColumnName("ban_reason");

                    b.Property<DateTime?>("BannedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("banned_at");

                    b.Property<long?>("BannedById")
                        .HasColumnType("bigint")
                        .HasColumnName("banned_by_id");

                    b.Property<DateTime?>("BannedUntil")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("banned_until");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(254)")
                        .HasColumnName("email");

                    b.Property<byte?>("FractionId")
                        .HasColumnType("smallint")
                        .HasColumnName("fraction_id");

                    b.Property<byte?>("FractionRankId")
                        .HasColumnType("smallint")
                        .HasColumnName("fraction_rank_id");

                    b.Property<string>("MuteReason")
                        .HasColumnType("text")
                        .HasColumnName("mute_reason");

                    b.Property<DateTime?>("MutedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("muted_at");

                    b.Property<long?>("MutedById")
                        .HasColumnType("bigint")
                        .HasColumnName("muted_by_id");

                    b.Property<DateTime?>("MutedUntil")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("muted_until");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("char(60)")
                        .HasColumnName("password");

                    b.HasKey("Id");

                    b.HasIndex("AdminRankId");

                    b.HasIndex("BannedById");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("FractionId");

                    b.HasIndex("FractionRankId");

                    b.HasIndex("MutedById");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("Gamemode.Repositories.Models.Weapon", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("Amount")
                        .HasColumnType("integer")
                        .HasColumnName("amount");

                    b.Property<long>("Hash")
                        .HasColumnType("bigint")
                        .HasColumnName("hash");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Hash")
                        .IsUnique();

                    b.ToTable("weapon");
                });

            modelBuilder.Entity("Gamemode.Repositories.Models.FractionRank", b =>
                {
                    b.HasOne("Gamemode.Repositories.Models.Fraction", "Fraction")
                        .WithMany()
                        .HasForeignKey("FractionId");

                    b.Navigation("Fraction");
                });

            modelBuilder.Entity("Gamemode.Repositories.Models.User", b =>
                {
                    b.HasOne("Gamemode.Repositories.Models.AdminRank", "AdminRank")
                        .WithMany()
                        .HasForeignKey("AdminRankId");

                    b.HasOne("Gamemode.Repositories.Models.User", "BannedBy")
                        .WithMany()
                        .HasForeignKey("BannedById");

                    b.HasOne("Gamemode.Repositories.Models.Fraction", "Fraction")
                        .WithMany()
                        .HasForeignKey("FractionId");

                    b.HasOne("Gamemode.Repositories.Models.FractionRank", "FractionRank")
                        .WithMany()
                        .HasForeignKey("FractionRankId");

                    b.HasOne("Gamemode.Repositories.Models.User", "MutedBy")
                        .WithMany()
                        .HasForeignKey("MutedById");

                    b.Navigation("AdminRank");

                    b.Navigation("BannedBy");

                    b.Navigation("Fraction");

                    b.Navigation("FractionRank");

                    b.Navigation("MutedBy");
                });

            modelBuilder.Entity("Gamemode.Repositories.Models.Weapon", b =>
                {
                    b.HasOne("Gamemode.Repositories.Models.User", "User")
                        .WithMany("Weapons")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Gamemode.Repositories.Models.User", b =>
                {
                    b.Navigation("Weapons");
                });
#pragma warning restore 612, 618
        }
    }
}
